---
- name: Build template isc-dhcp-server dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
  notify: "restart_dhcp_server"

- meta: flush_handlers

- name: Restart the dhcpd service
  systemd:
    name: isc-dhcp-server
    state: restarted
    enabled: yes
  register: dhcpd_restarted
  when:
    - dhcp_require_restart | default(false)

- name: Verify the dhcpd service is listening
  command: nmap --script broadcast-dhcp-discover
  when: dhcpd_restarted is changed
  register: dhcpd_start_attempt
  until: dhcpd_start_attempt.rc == 0
  retries: 5
  delay: 5

- name: Get dhcpd journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value isc-dhcp-server.service`
  register: isc_dhcpd_journal
  when: dhcpd_start_attempt.failed | default(false)

- fail:
    msg: "{{ isc_dhcpd_journal.stdout_lines }}"
  when: dhcpd_start_attempt.failed | default(false)
