---
- name: Build template isc-dhcp-server dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: "{{ isc_dhcp_server_configfile }}"
    backup: yes
    mode: 755
  notify: "restart_dhcp_server"

- name: Ensure dhcpd data directory is present with correct permissions
  file:
    path: "{{ isc_dhcp_server_confdir }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Restart the dhcpd service
  systemd:
    name: "{{ isc_dhcp_server_service }}"
    state: restarted
    enabled: yes
  register: dhcpd_restarted
  when:
    - dhcpd_require_restart | default(false)

- name: Verify the dhcpd service is listening
  command:
    cmd: 'nmap -sU -p 67  localhost --open | egrep -q "67/udp.*open"'
  register: dhcpd_start_attempt
  until: dhcpd_start_attempt.rc == 0
  retries: 5
  delay: 5
  changed_when: False

- name: Get dhcpd journald logs if service does not appear to be up
  shell: "journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value {{ isc_dhcp_server_service }}.service`"
  register: isc_dhcpd_journal
  when: dhcpd_start_attempt.failed | default(false)

- fail:
    msg: "{{ isc_dhcpd_journal.stdout_lines }}"
  when: dhcpd_start_attempt.failed | default(false)
