---
- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Configure Firewalld allowed ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ isc_dhcp_server_allowed_ports }}"
  when: ansible_os_family == "RedHat"

- name: Install isc-dhcp-server
  package:
    name: "{{ isc_dhcp_server_pkg }}"
    state: present

- name: "Create /etc/default file for isc-dhcp-server service"
  template:
    src: etc/default/isc-dhcp-server.j2
    dest: "/etc/default/{{ isc_dhcp_server_service }}"
    owner: root
    group: root
    mode: 0644
  notify: restart_dhcp_server

- name: Enable isc-dhcp-server service
  systemd:
    name: "{{ isc_dhcp_server_service }}"
    enabled: yes
    daemon_reload: yes
