---
- name: Install isc-dhcp-server
  package:
    name: "{{ isc_dhcp_server_pkg }}"
    state: present

- name: Enable isc-dhcp-server service
  systemd:
    name: "{{ isc_dhcp_server_service }}"
    enabled: yes
    daemon_reload: yes
