---
- name: Disable SELinux
  selinux:
    state: disabled
  when:
    - ansible_os_family == "RedHat"

- name: Get FirewallD public zone target
  command: firewall-cmd --zone public --get-target --permanent
  register: firewalld_public_target
  changed_when: False
  when:
    - ansible_os_family == "RedHat"

- name: Set FirewallD public zone to allow-all
  command: firewall-cmd --permanent --zone=public --set-target=ACCEPT
  when:
    - firewalld_public_target.stdout != "ACCEPT"
    - ansible_os_family == "RedHat"

- name: Install isc-dhcp-server
  package:
    name: "{{ isc_dhcp_server_pkg }}"
    state: present

- name: "Create /etc/default file for isc-dhcp-server service"
  template:
    src: etc/default/isc-dhcp-server.j2
    dest: "/etc/default/{{ isc_dhcp_server_service }}"
    owner: root
    group: root
    mode: 0644
  notify: restart_dhcp_server

- name: Enable isc-dhcp-server service
  systemd:
    name: "{{ isc_dhcp_server_service }}"
    enabled: yes
    daemon_reload: yes
