---
- name: install isc-dhcp-server
  package:
    name: "{{ isc_dhcp_server_pkg }}"
    state: present

- name: start isc-dhcp-server service
  systemd:
    name: "{{ isc_dhcp_server_service }}"
    state: started
    enabled: yes
